version: "3"

services:
    zeebe:
        image: camunda/zeebe:${CAMUNDA_CLOUD_VERSION:-1.0.0-rc3}
        container_name: zeebe
        environment:
            - zeebe.broker.exporters.elasticsearch.className=io.camunda.zeebe.exporter.ElasticsearchExporter
            - zeebe.broker.exporters.elasticsearch.args.url=http://elasticsearch:9200
            - zeebe.broker.exporters.elasticsearch.args.bulk.size=1
        ports:
            - 26500:26500
        volumes: 
            - zeebe:/usr/local/zeebe/data
        networks: 
            - camunda-cloud
        depends_on: 
            - elasticsearch

    operate:
        image: camunda/operate:${CAMUNDA_CLOUD_VERSION:-1.0.0-rc3}
        container_name: operate
        environment: 
            - camunda.operate.zeebe.gatewayAddress=zeebe:26500
            - camunda.operate.elasticsearch.url=http://elasticsearch:9200
            - camunda.operate.zeebeElasticsearch.url=http://elasticsearch:9200
        ports:
            - 8080:8080
        networks: 
            - camunda-cloud
        depends_on: 
            - elasticsearch

    tasklist:
        image: camunda/tasklist:${CAMUNDA_CLOUD_VERSION:-1.0.0-rc3}
        container_name: tasklist
        environment: 
            - camunda.tasklist.zeebe.gatewayAddress=zeebe:26500
            - camunda.tasklist.elasticsearch.url=http://elasticsearch:9200
            - camunda.tasklist.zeebeElasticsearch.url=http://elasticsearch:9200
        ports:
            - 8081:8080
        networks: 
            - camunda-cloud
        depends_on: 
            - elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.12.1}
        container_name: elasticsearch
        environment:
            - cluster.name=camunda-cloud
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - elastic:/usr/share/elasticsearch/data
        networks: 
            - camunda-cloud


volumes:
    zeebe:
        driver: local
    elastic:
        driver: local
    
networks:
    camunda-cloud:
        driver: bridge
